# This is an example parameter file for the AMST workflow
# Copy this parameter file to your desired location and adjust to your needs
# Then run the workflow using:
#    amst-run /path/to/my/params-amst-bspline.yaml

general:
  # These three can be omitted if AMST is run inside the same target folder as the pre-align >>>
  input_dirpath: /home/tatiana/test_data/prealignment # Defaults to <output_dirpath>/stack_to_ome_zarr/input-raw.ome.zarr
  pre_align_dirpath: /home/tatiana/squirrel/results/prealign/pre_alignment  # Defaults to <output_dirpath>/apply_pre_align/nsbs-pre-align.ome.zarr
    #pre_align_transforms: /path/to/pre-alignment-transforms.json  # Defaults to <output_dirpath>/nsbs-pre-align.json
  pre_align_transforms: /home/tatiana/squirrel/results/prealign/pre_alignment/nsbs-pre-align.json    #/path/to/pre-alignment-transforms.json  # Defaults to <output_dirpath>/nsbs-pre-align.json
    # <<<run
  output_dirpath: /home/tatiana/squirrel/results/amst
  cores: 8
  batch_size: 4
  max_cores_per_task: 4

amst:
  elastix_parameter_file: auto  #auto # Path to elastix parameter file, or "auto" to generate one
  transform: bspline
  median_radius: 7
  gaussian_sigma: 2.0
  auto_mask_off: false

apply_amst: {}

amst_to_tif_stack:
  active: true
